version: "3.8"
services:

  api:
    container_name: telzir_api_test
    env_file:
      - ./config/.env.api.test
    depends_on:
      - db_migrate
      - db_test
    command: tail -f /dev/null
    networks:
      - telzir-test
      
  db_migrate:
    command: prisma migrate deploy
    depends_on:
      - db_test
    env_file:
      - ./config/.env.api.test
    networks:
      - telzir-test

  db_test:
    container_name: telzir_db_test
    image: postgres:13
    restart: always
    env_file:
      - ./config/.env.postgresql
    ports:
      - 5435:5432
    networks:
      - telzir-test

networks:
  telzir-test:
    driver: bridge