version: "3.8"
services:

  api:
    container_name: telzir_api
    build:
      context: ./nest
      target: development
    env_file:
      - ./config/.env.api
    ports:
      - 9000:3000
    volumes:
      - ./nest:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - telzir-development
    command: npm run start:dev

  db:
    container_name: telzir_db
    image: postgres:13
    restart: always
    env_file:
      - ./config/.env.postgresql
    ports:
      - 5434:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - telzir-development

  prisma-migrate:
    networks:
      - telzir-development
    depends_on:
      - db

networks:
  telzir-development:
    driver: bridge
  
volumes:
  postgres:
    name: telzir-db
